#!/usr/bin/env python
"""Generate the baseline-adaptation fairness audit table for revision."""

from __future__ import annotations

import csv
from pathlib import Path


ROWS = [
    {
        "Group": "Forecasting-only baselines",
        "Methods": "STResNet; STDN; DeepSTN; DeepCrowd; DualST",
        "Adaptation": "Replace the UFP coarse-grained prediction module; then feed the predicted coarse map to the same FUFI/SR module.",
        "Shared information": "Same completed coarse-grained history, same train/validation/test split, same prediction horizon, same future fine-grained target.",
        "Validation rule": "Hyperparameters are selected on the validation split; no test-set metric is used for model or completion selection.",
    },
    {
        "Group": "Super-resolution-only baselines",
        "Methods": "UrbanFM; UrbanPy; FODE; UrbanODE; CUFAR",
        "Adaptation": "Replace the FUFI/SR module; receive the same predicted coarse-grained future map generated by the UFP branch.",
        "Shared information": "Same coarse prediction input, same upscaling factor, same fine-grained target, same split and evaluation metrics.",
        "Validation rule": "SR-specific hyperparameters are tuned on validation data under the same prediction-before-SR pipeline.",
    },
    {
        "Group": "End-to-end HR forecasting",
        "Methods": "HRSTTs",
        "Adaptation": "Use as a direct end-to-end high-resolution forecasting baseline from coarse-grained historical observations.",
        "Shared information": "Same historical coarse input window, flow-only controlled input, same future fine-grained target and splits.",
        "Validation rule": "Trained and selected using the validation split; reported as the closest direct end-to-end reference.",
    },
    {
        "Group": "Missing-completion baselines",
        "Methods": "No completion; zero; mean; linear; KNN; SVD",
        "Adaptation": "Apply the completion operator before downstream prediction/inference or evaluate completion MSE on synthetic missing entries.",
        "Shared information": "Same synthetic mask, same missing rate, same random seeds, same observed entries, and same held-out missing labels.",
        "Validation rule": "The adaptive selector is chosen on validation completion MSE and fixed before test evaluation.",
    },
    {
        "Group": "FUPSI",
        "Methods": "Validation-fixed completion + UFP + SR + GAN regularization",
        "Adaptation": "Full proposed pipeline: completion, coarse-grained prediction, and fine-grained super-resolution.",
        "Shared information": "Uses the same flow input, split, target, mask protocol, and metrics; the optional external-factor branch is disabled in regenerated MainSeed runs.",
        "Validation rule": "Completion choice and hyperparameters are fixed from validation data; discriminator is used only during training.",
    },
]


def write_csv(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(ROWS[0].keys()))
        writer.writeheader()
        writer.writerows(ROWS)


def write_markdown(path: Path) -> None:
    headers = list(ROWS[0].keys())
    lines = [
        "# Baseline Adaptation and Fairness Protocol",
        "",
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for row in ROWS:
        lines.append("| " + " | ".join(row[h] for h in headers) + " |")
    lines.append("")
    lines.append(
        "Note: this table documents adaptation and validation rules. Training-time, inference-time, and peak-memory comparisons for all baselines should be filled after the three-seed reruns on the same hardware."
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def latex_escape(text: str) -> str:
    return (
        text.replace("&", r"\&")
        .replace("%", r"\%")
        .replace("_", r"\_")
    )


def write_latex(path: Path) -> None:
    lines = [
        r"\begin{table*}[!htbp]",
        r"\centering",
        r"\caption{Baseline adaptation and fairness protocol.}",
        r"\label{tab:baseline-adaptation}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\renewcommand{\arraystretch}{1.08}",
        r"\begin{tabular}{>{\raggedright\arraybackslash}p{2.2cm}>{\raggedright\arraybackslash}p{2.4cm}>{\raggedright\arraybackslash}p{4.5cm}>{\raggedright\arraybackslash}p{2.8cm}}",
        r"\toprule",
        r"Group & Methods & Unified-task adaptation and shared information & Validation/budget rule \\",
        r"\midrule",
    ]
    for row in ROWS:
        adaptation = f"{row['Adaptation']} {row['Shared information']}"
        lines.append(
            " & ".join(
                [
                    latex_escape(row["Group"]),
                    latex_escape(row["Methods"]),
                    latex_escape(adaptation),
                    latex_escape(row["Validation rule"]),
                ]
            )
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table*}",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    output_dir = Path("revision/fairness")
    write_csv(output_dir / "baseline_adaptation_fairness_protocol.csv")
    write_markdown(output_dir / "baseline_adaptation_fairness_protocol.md")
    write_latex(output_dir / "baseline_adaptation_fairness_protocol_table.tex")
    print(f"Wrote fairness audit files to {output_dir}")


if __name__ == "__main__":
    main()
